name: CustomSpawn
version: 1.0
main: com.example.customspawn.CustomSpawn
api-version: '1.21'
commands:
  setspawn:
    description: Ustawia miejsce spawnu
    permission: customspawn.setspawn
  spawn:
    description: Teleportuje na spawn po ustawionym czasie
