name: manius_Spawn
version: 1.0
main: pl.s16.spawn.Main
api-version: '1.20'
commands:
  spawn:
    description: Teleportuje na spawn serwera.
    usage: /spawn
  setspawn:
    description: Ustawia punkt spawnu serwera.
    usage: /setspawn
    permission: s16.admin
permissions:
  s16.admin:
    description: Dostęp do komend administracyjnych S16
    default: op
